name = "DirichletProblem"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DirichletProblem"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
maxSynthPendingDepth = 3
weak.linter.flexible = true
weak.linter.mathlibStandardSet = true
warn.sorry = false


[[require]]
name = "verso"
scope = "leanprover"
rev = "v4.34.0-rc2"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "ac7917d6a517b3b710987e9f8037bdcac522a461"

[[lean_lib]]
name = "DirichletProblem"

[[lean_exe]]
name = "generate-docs"
root = "Manual"
